### ISSUE TITLE
Coudn't figure out the error

### ISSUE THREAD

**Issue by saifeemustafaq** [saifeemustafaq/azurefunctions_covid19#1]
# [Create a function in Azure using Visual Studio Code](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-python#feedback)

After doing the following steps:

-    Select a language for your function project: Choose Python.

-    Select a Python alias to create a virtual environment: Choose the location of your Python interpreter. If the location isn't shown, type in the full path to your Python binary.

-    Select a template for your project's first function: Choose HTTP trigger.

-    Provide a function name: Type HttpExample.

-    Authorization level: Choose Anonymous, which enables anyone to call your function endpoint. To learn about authorization level, see Authorization keys.

-    Select how you would like to open your project: Choose Add to workspace.

---
I press *F5* to ***Run the function locally***

And this is the error I get:
![Screenshot (72)](https://user-images.githubusercontent.com/15520369/82123809-f0ec0e00-97b8-11ea-8065-884c173c1020.png)

I have python, pip, wheel, azure-function tools installed

`PS C:\Users\Mustafa Saifee\azfunc> python --version  `
`Python 3.8.2`

`PS C:\Users\Mustafa Saifee\azfunc> pip --version  `
`pip 20.1 from c:\program files\python38\lib\site-packages\pip (python 3.8)`

`PS C:\Users\Mustafa Saifee\azfunc> wheel version  `
`wheel 0.34.2`

`PS C:\Users\Mustafa Saifee\azfunc> pip install azure-functions  `
`Requirement already satisfied: azure-functions in c:\program files\python38\lib\site-packages (1.2.1)`

Operating System: Microsoft Windows 10 Education 10.0.19041 Build 19041

**Comment by aprilgittens** [comment]
Azure Functions supports Python 3.8, 3.7 and 3.6. However, you must ensure that your Python version is 64-bit. Using 32-bit will cause version errors.

If your Python 3.8 is 64-bit and you're still receiving errors, try downloading 3.7 64-bit, create a virtual environment using Python 3.7 and then run the code there.

**Comment by saifeemustafaq** [comment]
PS C:\Users\Mustafa Saifee\azfunc> py
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by saifeemustafaq** [comment]
I tried python 3.7 and 3.8
plus I also tried it with the conda based python.
Then I uninstalled everything. And one by one installed it back. Still the issue persists

**Comment by aprilgittens** [comment]
Ok, I've gotten it to work with 3.8 x64
Do you have Node.js installed?
And were you asked at any point to install Azure Functions Core Tools? If so, did you install it?

**Comment by aprilgittens** [comment]
Also, have you tried running the function while the `__init__.py` file is active on the screen?

There shouldn't be a need to modify anything in the `function.json` file if you're trying out the Quickstart. Therefore, ensure that you're looking at the `__init__.py` file when you Start Debugging (F5).

**Comment by saifeemustafaq** [comment]
> 
> 
> Also, have you tried running the function while the `__init__.py` file is active on the screen?
> 
> There shouldn't be a need to modify anything in the `function.json` file if you're trying out the Quickstart. Therefore, ensure that you're looking at the `__init__.py` file when you Start Debugging (F5).

Yes, this solved my problem. Thank You so much @aprilspeight . Although there are new errors now.

Now after the program is successfully executed, the browser opens up and displays:

> `Please pass a name on the query string or in the request body`

**Comment by aprilgittens** [comment]
Great! Make sure to be on the `__init__.py` file whenever you run the trigger. Otherwise, VS Code will try to run whatever file is currently in the active window.

This new problem is a quick fix! The QuickStart author needs to update the instructions as they forgot to mention what to do here.

You need to insert `?name=Mustafa` into the URL that’s in the address bar. Once you do that and refresh the page, the webpage should say `Hello, {name}. This HTTP triggered function executed successfully.`

What’s happening is that the code is looking for a query string parameter to be added at the end of the URL. Therefore, you must add one to the end of the URL using `?name=` and insert either your name or any name directly after the equal sign.

When you refresh the page, the function triggers because you’re making a HTTP request which updates the webpage. If you look at the terminal in VS Code, you’ll see that the function is triggered each time you refresh the webpage.

**Comment by saifeemustafaq** [comment]
Thank You so much, I will do this in a while and update back to you. Thank You
Should I/Am I supposed to report it to the Quickstart Author?
